/**
 * Icon Registry — name-to-component mapping for Lucide icons.
 *
 * Separated from Icon.tsx so that non-component consumers (e.g. useNavRoutes)
 * can import the registry without triggering react-refresh violations.
 */

import {
  Accessibility,
  Activity,
  AlertCircle,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BarChart3,
  Bold,
  Book,
  Bookmark,
  Box,
  Brain,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clipboard,
  Clock,
  Columns,
  Component,
  Copy,
  CornerDownLeft,
  Cpu,
  Database,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCode,
  FileCog,
  FileImage,
  FileJson,
  FileText,
  FlaskConical,
  Folder,
  FolderOpen,
  Globe,
  Grid,
  Grip,
  GripVertical,
  Hand,
  Heart,
  HelpCircle,
  Home,
  Info,
  Italic,
  Keyboard,
  Layers,
  Layout,
  LayoutGrid,
  LayoutList,
  Link,
  List,
  Loader2,
  Lock,
  Mail,
  Menu,
  Minus,
  Monitor,
  MoreHorizontal,
  MoreVertical,
  MousePointer2,
  Package,
  Pause,
  Pencil,
  Play,
  Plus,
  Redo2,
  Rows,
  Search,
  Server,
  Settings,
  SkipBack,
  SkipForward,
  Smartphone,
  Square,
  Star,
  Strikethrough,
  Tag,
  Terminal,
  TestTube2,
  Trash2,
  Underline,
  Undo2,
  Unlock,
  User,
  Users,
  Volume2,
  VolumeX,
  Wand2,
  X,
  XCircle,
  Zap,
} from "lucide-react";

/**
 * Icon name registry
 * Add new icons here as needed
 */
export const icons = {
  // App Specific
  accessibility: Accessibility,
  book: Book,
  component: Component,
  flask: FlaskConical,
  layout: Layout,
  package: Package,
  "test-tube": TestTube2,

  // File/Folder
  folder: Folder,
  "folder-open": FolderOpen,
  file: File,
  "file-text": FileText,
  "file-code": FileCode,
  "file-cog": FileCog,
  "file-image": FileImage,
  "file-json": FileJson,

  // Navigation
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "chevron-left": ChevronLeft,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,

  // Actions
  plus: Plus,
  minus: Minus,
  x: X,
  check: Check,
  trash: Trash2,
  pencil: Pencil,
  copy: Copy,
  clipboard: Clipboard,

  // UI
  search: Search,
  settings: Settings,
  menu: Menu,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,
  grip: Grip,
  "grip-vertical": GripVertical,

  // Media
  play: Play,
  pause: Pause,
  "skip-forward": SkipForward,
  "skip-back": SkipBack,
  volume: Volume2,
  "volume-muted": VolumeX,

  // Status
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  info: Info,
  help: HelpCircle,
  "check-circle": CheckCircle,
  "x-circle": XCircle,
  loader: Loader2,

  // Common
  user: User,
  users: Users,
  mail: Mail,
  calendar: Calendar,
  clock: Clock,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  tag: Tag,
  link: Link,
  "external-link": ExternalLink,

  // Layout
  home: Home,
  list: List,
  grid: Grid,
  columns: Columns,
  rows: Rows,
  "layout-grid": LayoutGrid,
  "layout-list": LayoutList,

  // Editing
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  "align-left": AlignLeft,
  "align-center": AlignCenter,
  "align-right": AlignRight,
  "align-justify": AlignJustify,

  // Misc
  eye: Eye,
  "eye-off": EyeOff,
  lock: Lock,
  unlock: Unlock,
  zap: Zap,
  wand: Wand2,
  "bar-chart": BarChart3,
  database: Database,
  server: Server,
  box: Box,
  layers: Layers,
  globe: Globe,
  brain: Brain,
  monitor: Monitor,
  smartphone: Smartphone,
  cursor: MousePointer2,
  hand: Hand,
  square: Square,
  undo: Undo2,
  redo: Redo2,
  enter: CornerDownLeft,
  keyboard: Keyboard,
  terminal: Terminal,
  cpu: Cpu,
  activity: Activity,
} as const;

export type IconName = keyof typeof icons;

/** All registered icon names — used by matchIconName for fuzzy search */
export const iconNames: IconName[] = Object.keys(icons) as IconName[];
