import type { KanbanState } from "@apps/kanban/model/types";

export const INITIAL_STATE: KanbanState = {
  data: {
    board: {
      id: "board-1",
      title: "Product Roadmap",
      description: "Q1 2026 Feature Roadmap",
    },
    columns: {
      "col-backlog": {
        id: "col-backlog",
        title: "Backlog",
        color: "#6366f1",
        wipLimit: null,
        collapsed: false,
      },
      "col-todo": {
        id: "col-todo",
        title: "To Do",
        color: "#3b82f6",
        wipLimit: 5,
        collapsed: false,
      },
      "col-progress": {
        id: "col-progress",
        title: "In Progress",
        color: "#f97316",
        wipLimit: 3,
        collapsed: false,
      },
      "col-review": {
        id: "col-review",
        title: "Review",
        color: "#8b5cf6",
        wipLimit: 2,
        collapsed: false,
      },
      "col-done": {
        id: "col-done",
        title: "Done",
        color: "#10b981",
        wipLimit: null,
        collapsed: false,
      },
    },
    columnOrder: [
      "col-backlog",
      "col-todo",
      "col-progress",
      "col-review",
      "col-done",
    ],
    cards: {
      "card-1": {
        id: "card-1",
        title: "Design system tokens",
        description: "Define color, spacing, and typography tokens",
        priority: "high",
        labels: ["label-design"],
        assignee: "Alice",
        dueDate: "2026-02-15",
        columnId: "col-done",
        createdAt: 1738800000000,
      },
      "card-2": {
        id: "card-2",
        title: "User authentication flow",
        description: "Implement OAuth2 + JWT",
        priority: "urgent",
        labels: ["label-backend", "label-security"],
        assignee: "Bob",
        dueDate: "2026-02-20",
        columnId: "col-progress",
        createdAt: 1738800100000,
      },
      "card-3": {
        id: "card-3",
        title: "Dashboard analytics view",
        description: "Charts and KPI widgets",
        priority: "medium",
        labels: ["label-frontend"],
        assignee: "Alice",
        dueDate: "2026-03-01",
        columnId: "col-todo",
        createdAt: 1738800200000,
      },
      "card-4": {
        id: "card-4",
        title: "API rate limiting",
        description: "Implement token bucket algorithm",
        priority: "high",
        labels: ["label-backend"],
        assignee: "Charlie",
        dueDate: "2026-02-25",
        columnId: "col-progress",
        createdAt: 1738800300000,
      },
      "card-5": {
        id: "card-5",
        title: "Mobile responsive layout",
        description: "Adapt all views for mobile breakpoints",
        priority: "medium",
        labels: ["label-frontend", "label-design"],
        assignee: null,
        dueDate: null,
        columnId: "col-backlog",
        createdAt: 1738800400000,
      },
      "card-6": {
        id: "card-6",
        title: "E2E test suite",
        description: "Playwright tests for critical paths",
        priority: "low",
        labels: ["label-testing"],
        assignee: "Diana",
        dueDate: "2026-03-15",
        columnId: "col-backlog",
        createdAt: 1738800500000,
      },
      "card-7": {
        id: "card-7",
        title: "Search & filter engine",
        description: "Full-text search with faceted filters",
        priority: "high",
        labels: ["label-backend", "label-frontend"],
        assignee: "Bob",
        dueDate: "2026-02-28",
        columnId: "col-review",
        createdAt: 1738800600000,
      },
      "card-8": {
        id: "card-8",
        title: "Notification system",
        description: "Real-time notifications via WebSocket",
        priority: "medium",
        labels: ["label-backend"],
        assignee: null,
        dueDate: null,
        columnId: "col-todo",
        createdAt: 1738800700000,
      },
      "card-9": {
        id: "card-9",
        title: "Onboarding wizard",
        description: "Step-by-step new user guide",
        priority: "low",
        labels: ["label-frontend", "label-design"],
        assignee: "Alice",
        dueDate: "2026-03-10",
        columnId: "col-backlog",
        createdAt: 1738800800000,
      },
      "card-10": {
        id: "card-10",
        title: "Performance audit",
        description: "Lighthouse scores + bundle analysis",
        priority: "none",
        labels: ["label-testing"],
        assignee: "Charlie",
        dueDate: null,
        columnId: "col-todo",
        createdAt: 1738800900000,
      },
    },
    cardOrder: {
      "col-backlog": ["card-5", "card-6", "card-9"],
      "col-todo": ["card-3", "card-8", "card-10"],
      "col-progress": ["card-2", "card-4"],
      "col-review": ["card-7"],
      "col-done": ["card-1"],
    },
    labels: {
      "label-frontend": {
        id: "label-frontend",
        name: "Frontend",
        color: "#3b82f6",
      },
      "label-backend": {
        id: "label-backend",
        name: "Backend",
        color: "#10b981",
      },
      "label-design": { id: "label-design", name: "Design", color: "#ec4899" },
      "label-security": {
        id: "label-security",
        name: "Security",
        color: "#f43f5e",
      },
      "label-testing": {
        id: "label-testing",
        name: "Testing",
        color: "#f97316",
      },
    },
  },
  ui: {
    editingCardId: null,
    editDraft: "",
    drafts: {},
    searchQuery: "",
    priorityFilter: null,
    labelFilter: null,
    editingColumnId: null,
    columnEditDraft: "",
    detailCardId: null,
    actionMenuCardId: null,
    selectedCardIds: [],
    bulkMenuOpen: null,
  },
  effects: [],
  history: {
    past: [],
    future: [],
  },
};
