/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodoRouteImport } from './routes/_todo'
import { Route as MinimalRouteImport } from './routes/_minimal'
import { Route as TodoIndexRouteImport } from './routes/_todo/index'
import { Route as MinimalTodoRouteImport } from './routes/_minimal/todo'
import { Route as MinimalDocsRouteImport } from './routes/_minimal/docs'
import { Route as MinimalBuilderListRouteImport } from './routes/_minimal/builder-list'
import { Route as MinimalBuilderRouteImport } from './routes/_minimal/builder'
import { Route as MinimalDocsIndexRouteImport } from './routes/_minimal/docs/index'
import { Route as MinimalPlaygroundTestbotRouteImport } from './routes/_minimal/playground.testbot'
import { Route as MinimalPlaygroundRadixRouteImport } from './routes/_minimal/playground.radix'
import { Route as MinimalPlaygroundQuickpickRouteImport } from './routes/_minimal/playground.quickpick'
import { Route as MinimalPlaygroundKernelRouteImport } from './routes/_minimal/playground.kernel'
import { Route as MinimalPlaygroundFocusRouteImport } from './routes/_minimal/playground.focus'
import { Route as MinimalPlaygroundCommandPaletteRouteImport } from './routes/_minimal/playground.command-palette'
import { Route as MinimalPlaygroundAriaRouteImport } from './routes/_minimal/playground.aria'
import { Route as MinimalPlaygroundApgRouteImport } from './routes/_minimal/playground.apg'

const TodoRoute = TodoRouteImport.update({
  id: '/_todo',
  getParentRoute: () => rootRouteImport,
} as any)
const MinimalRoute = MinimalRouteImport.update({
  id: '/_minimal',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoIndexRoute = TodoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TodoRoute,
} as any)
const MinimalTodoRoute = MinimalTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => MinimalRoute,
} as any)
const MinimalDocsRoute = MinimalDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => MinimalRoute,
} as any)
const MinimalBuilderListRoute = MinimalBuilderListRouteImport.update({
  id: '/builder-list',
  path: '/builder-list',
  getParentRoute: () => MinimalRoute,
} as any)
const MinimalBuilderRoute = MinimalBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => MinimalRoute,
} as any)
const MinimalDocsIndexRoute = MinimalDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MinimalDocsRoute,
} as any)
const MinimalPlaygroundTestbotRoute =
  MinimalPlaygroundTestbotRouteImport.update({
    id: '/playground/testbot',
    path: '/playground/testbot',
    getParentRoute: () => MinimalRoute,
  } as any)
const MinimalPlaygroundRadixRoute = MinimalPlaygroundRadixRouteImport.update({
  id: '/playground/radix',
  path: '/playground/radix',
  getParentRoute: () => MinimalRoute,
} as any)
const MinimalPlaygroundQuickpickRoute =
  MinimalPlaygroundQuickpickRouteImport.update({
    id: '/playground/quickpick',
    path: '/playground/quickpick',
    getParentRoute: () => MinimalRoute,
  } as any)
const MinimalPlaygroundKernelRoute = MinimalPlaygroundKernelRouteImport.update({
  id: '/playground/kernel',
  path: '/playground/kernel',
  getParentRoute: () => MinimalRoute,
} as any)
const MinimalPlaygroundFocusRoute = MinimalPlaygroundFocusRouteImport.update({
  id: '/playground/focus',
  path: '/playground/focus',
  getParentRoute: () => MinimalRoute,
} as any)
const MinimalPlaygroundCommandPaletteRoute =
  MinimalPlaygroundCommandPaletteRouteImport.update({
    id: '/playground/command-palette',
    path: '/playground/command-palette',
    getParentRoute: () => MinimalRoute,
  } as any)
const MinimalPlaygroundAriaRoute = MinimalPlaygroundAriaRouteImport.update({
  id: '/playground/aria',
  path: '/playground/aria',
  getParentRoute: () => MinimalRoute,
} as any)
const MinimalPlaygroundApgRoute = MinimalPlaygroundApgRouteImport.update({
  id: '/playground/apg',
  path: '/playground/apg',
  getParentRoute: () => MinimalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TodoIndexRoute
  '/builder': typeof MinimalBuilderRoute
  '/builder-list': typeof MinimalBuilderListRoute
  '/docs': typeof MinimalDocsRouteWithChildren
  '/todo': typeof MinimalTodoRoute
  '/playground/apg': typeof MinimalPlaygroundApgRoute
  '/playground/aria': typeof MinimalPlaygroundAriaRoute
  '/playground/command-palette': typeof MinimalPlaygroundCommandPaletteRoute
  '/playground/focus': typeof MinimalPlaygroundFocusRoute
  '/playground/kernel': typeof MinimalPlaygroundKernelRoute
  '/playground/quickpick': typeof MinimalPlaygroundQuickpickRoute
  '/playground/radix': typeof MinimalPlaygroundRadixRoute
  '/playground/testbot': typeof MinimalPlaygroundTestbotRoute
  '/docs/': typeof MinimalDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof TodoIndexRoute
  '/builder': typeof MinimalBuilderRoute
  '/builder-list': typeof MinimalBuilderListRoute
  '/todo': typeof MinimalTodoRoute
  '/playground/apg': typeof MinimalPlaygroundApgRoute
  '/playground/aria': typeof MinimalPlaygroundAriaRoute
  '/playground/command-palette': typeof MinimalPlaygroundCommandPaletteRoute
  '/playground/focus': typeof MinimalPlaygroundFocusRoute
  '/playground/kernel': typeof MinimalPlaygroundKernelRoute
  '/playground/quickpick': typeof MinimalPlaygroundQuickpickRoute
  '/playground/radix': typeof MinimalPlaygroundRadixRoute
  '/playground/testbot': typeof MinimalPlaygroundTestbotRoute
  '/docs': typeof MinimalDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_minimal': typeof MinimalRouteWithChildren
  '/_todo': typeof TodoRouteWithChildren
  '/_minimal/builder': typeof MinimalBuilderRoute
  '/_minimal/builder-list': typeof MinimalBuilderListRoute
  '/_minimal/docs': typeof MinimalDocsRouteWithChildren
  '/_minimal/todo': typeof MinimalTodoRoute
  '/_todo/': typeof TodoIndexRoute
  '/_minimal/playground/apg': typeof MinimalPlaygroundApgRoute
  '/_minimal/playground/aria': typeof MinimalPlaygroundAriaRoute
  '/_minimal/playground/command-palette': typeof MinimalPlaygroundCommandPaletteRoute
  '/_minimal/playground/focus': typeof MinimalPlaygroundFocusRoute
  '/_minimal/playground/kernel': typeof MinimalPlaygroundKernelRoute
  '/_minimal/playground/quickpick': typeof MinimalPlaygroundQuickpickRoute
  '/_minimal/playground/radix': typeof MinimalPlaygroundRadixRoute
  '/_minimal/playground/testbot': typeof MinimalPlaygroundTestbotRoute
  '/_minimal/docs/': typeof MinimalDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/builder-list'
    | '/docs'
    | '/todo'
    | '/playground/apg'
    | '/playground/aria'
    | '/playground/command-palette'
    | '/playground/focus'
    | '/playground/kernel'
    | '/playground/quickpick'
    | '/playground/radix'
    | '/playground/testbot'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/builder-list'
    | '/todo'
    | '/playground/apg'
    | '/playground/aria'
    | '/playground/command-palette'
    | '/playground/focus'
    | '/playground/kernel'
    | '/playground/quickpick'
    | '/playground/radix'
    | '/playground/testbot'
    | '/docs'
  id:
    | '__root__'
    | '/_minimal'
    | '/_todo'
    | '/_minimal/builder'
    | '/_minimal/builder-list'
    | '/_minimal/docs'
    | '/_minimal/todo'
    | '/_todo/'
    | '/_minimal/playground/apg'
    | '/_minimal/playground/aria'
    | '/_minimal/playground/command-palette'
    | '/_minimal/playground/focus'
    | '/_minimal/playground/kernel'
    | '/_minimal/playground/quickpick'
    | '/_minimal/playground/radix'
    | '/_minimal/playground/testbot'
    | '/_minimal/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MinimalRoute: typeof MinimalRouteWithChildren
  TodoRoute: typeof TodoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_todo': {
      id: '/_todo'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_minimal': {
      id: '/_minimal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MinimalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_todo/': {
      id: '/_todo/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TodoIndexRouteImport
      parentRoute: typeof TodoRoute
    }
    '/_minimal/todo': {
      id: '/_minimal/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof MinimalTodoRouteImport
      parentRoute: typeof MinimalRoute
    }
    '/_minimal/docs': {
      id: '/_minimal/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof MinimalDocsRouteImport
      parentRoute: typeof MinimalRoute
    }
    '/_minimal/builder-list': {
      id: '/_minimal/builder-list'
      path: '/builder-list'
      fullPath: '/builder-list'
      preLoaderRoute: typeof MinimalBuilderListRouteImport
      parentRoute: typeof MinimalRoute
    }
    '/_minimal/builder': {
      id: '/_minimal/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof MinimalBuilderRouteImport
      parentRoute: typeof MinimalRoute
    }
    '/_minimal/docs/': {
      id: '/_minimal/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof MinimalDocsIndexRouteImport
      parentRoute: typeof MinimalDocsRoute
    }
    '/_minimal/playground/testbot': {
      id: '/_minimal/playground/testbot'
      path: '/playground/testbot'
      fullPath: '/playground/testbot'
      preLoaderRoute: typeof MinimalPlaygroundTestbotRouteImport
      parentRoute: typeof MinimalRoute
    }
    '/_minimal/playground/radix': {
      id: '/_minimal/playground/radix'
      path: '/playground/radix'
      fullPath: '/playground/radix'
      preLoaderRoute: typeof MinimalPlaygroundRadixRouteImport
      parentRoute: typeof MinimalRoute
    }
    '/_minimal/playground/quickpick': {
      id: '/_minimal/playground/quickpick'
      path: '/playground/quickpick'
      fullPath: '/playground/quickpick'
      preLoaderRoute: typeof MinimalPlaygroundQuickpickRouteImport
      parentRoute: typeof MinimalRoute
    }
    '/_minimal/playground/kernel': {
      id: '/_minimal/playground/kernel'
      path: '/playground/kernel'
      fullPath: '/playground/kernel'
      preLoaderRoute: typeof MinimalPlaygroundKernelRouteImport
      parentRoute: typeof MinimalRoute
    }
    '/_minimal/playground/focus': {
      id: '/_minimal/playground/focus'
      path: '/playground/focus'
      fullPath: '/playground/focus'
      preLoaderRoute: typeof MinimalPlaygroundFocusRouteImport
      parentRoute: typeof MinimalRoute
    }
    '/_minimal/playground/command-palette': {
      id: '/_minimal/playground/command-palette'
      path: '/playground/command-palette'
      fullPath: '/playground/command-palette'
      preLoaderRoute: typeof MinimalPlaygroundCommandPaletteRouteImport
      parentRoute: typeof MinimalRoute
    }
    '/_minimal/playground/aria': {
      id: '/_minimal/playground/aria'
      path: '/playground/aria'
      fullPath: '/playground/aria'
      preLoaderRoute: typeof MinimalPlaygroundAriaRouteImport
      parentRoute: typeof MinimalRoute
    }
    '/_minimal/playground/apg': {
      id: '/_minimal/playground/apg'
      path: '/playground/apg'
      fullPath: '/playground/apg'
      preLoaderRoute: typeof MinimalPlaygroundApgRouteImport
      parentRoute: typeof MinimalRoute
    }
  }
}

interface MinimalDocsRouteChildren {
  MinimalDocsIndexRoute: typeof MinimalDocsIndexRoute
}

const MinimalDocsRouteChildren: MinimalDocsRouteChildren = {
  MinimalDocsIndexRoute: MinimalDocsIndexRoute,
}

const MinimalDocsRouteWithChildren = MinimalDocsRoute._addFileChildren(
  MinimalDocsRouteChildren,
)

interface MinimalRouteChildren {
  MinimalBuilderRoute: typeof MinimalBuilderRoute
  MinimalBuilderListRoute: typeof MinimalBuilderListRoute
  MinimalDocsRoute: typeof MinimalDocsRouteWithChildren
  MinimalTodoRoute: typeof MinimalTodoRoute
  MinimalPlaygroundApgRoute: typeof MinimalPlaygroundApgRoute
  MinimalPlaygroundAriaRoute: typeof MinimalPlaygroundAriaRoute
  MinimalPlaygroundCommandPaletteRoute: typeof MinimalPlaygroundCommandPaletteRoute
  MinimalPlaygroundFocusRoute: typeof MinimalPlaygroundFocusRoute
  MinimalPlaygroundKernelRoute: typeof MinimalPlaygroundKernelRoute
  MinimalPlaygroundQuickpickRoute: typeof MinimalPlaygroundQuickpickRoute
  MinimalPlaygroundRadixRoute: typeof MinimalPlaygroundRadixRoute
  MinimalPlaygroundTestbotRoute: typeof MinimalPlaygroundTestbotRoute
}

const MinimalRouteChildren: MinimalRouteChildren = {
  MinimalBuilderRoute: MinimalBuilderRoute,
  MinimalBuilderListRoute: MinimalBuilderListRoute,
  MinimalDocsRoute: MinimalDocsRouteWithChildren,
  MinimalTodoRoute: MinimalTodoRoute,
  MinimalPlaygroundApgRoute: MinimalPlaygroundApgRoute,
  MinimalPlaygroundAriaRoute: MinimalPlaygroundAriaRoute,
  MinimalPlaygroundCommandPaletteRoute: MinimalPlaygroundCommandPaletteRoute,
  MinimalPlaygroundFocusRoute: MinimalPlaygroundFocusRoute,
  MinimalPlaygroundKernelRoute: MinimalPlaygroundKernelRoute,
  MinimalPlaygroundQuickpickRoute: MinimalPlaygroundQuickpickRoute,
  MinimalPlaygroundRadixRoute: MinimalPlaygroundRadixRoute,
  MinimalPlaygroundTestbotRoute: MinimalPlaygroundTestbotRoute,
}

const MinimalRouteWithChildren =
  MinimalRoute._addFileChildren(MinimalRouteChildren)

interface TodoRouteChildren {
  TodoIndexRoute: typeof TodoIndexRoute
}

const TodoRouteChildren: TodoRouteChildren = {
  TodoIndexRoute: TodoIndexRoute,
}

const TodoRouteWithChildren = TodoRoute._addFileChildren(TodoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MinimalRoute: MinimalRouteWithChildren,
  TodoRoute: TodoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
